services:
  app:
    image: hashimgujjar/notes_test_repo:latest
    ports:
      - "3001:8080"
    networks:
      - notes-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - notes-network
    volumes:
      - mongo-data:/data/db

networks:
  notes-network:
    driver: bridge

volumes:
  mongo-data:
